export const breaking = [
  {
    channel_logo: "https://placehold.co/36x36",
    title: "Planet with potential for life discovered 5 light-years away",
    channel_name: "Nancy",
    views: "63M",
    upload_date: "9 hours ago",
    thumbnail: "https://placehold.co/310x175",
  },
  {
    channel_logo: "https://placehold.co/36x36",
    title: "Intensifying global warming leads to widespread coral bleaching across the globe",
    channel_name: "ABC",
    views: "44M",
    upload_date: "9 hours ago",
    thumbnail: "https://placehold.co/310x175",
  },
  {
    channel_logo: "https://placehold.co/36x36",
    title: "US government declares war on ant army in Texas",
    channel_name: "NNN",
    views: "25K",
    upload_date: "4 months ago",
    thumbnail: "https://placehold.co/310x175",
  },
  {
    channel_logo: "https://placehold.co/36x36",
    title: "Thailand experiences record-breaking heatwave, reaching 50 degrees Celsius",
    channel_name: "Toirath",
    views: "43K",
    upload_date: "3 days ago",
    thumbnail: "https://placehold.co/310x175",
  },
  {
    channel_logo: "https://placehold.co/36x36",
    title: "China's largest bank declares bankruptcy",
    channel_name: "Gime",
    views: "805",
    upload_date: "2 hours ago",
    thumbnail: "https://placehold.co/310x175",
  },
];
